1. Study of Fuzzy Operations

In [4]:
A = {10,11,12,13}
B = {11,12,13,14,15}

# UNION
Union = A.union(B)
print(Union) #{10, 11, 12, 13, 14, 15}

# INTERSECTION
Intersection = A.intersection(B)
print(Intersection) #{11, 12, 13}

# COMPLEMENT
Complement = B - A
print(Complement) #{14, 15}

# ALGEBRIC SUM
A = {0.2/1 + 0.3/2 + 0.4/3 + 0.5/4}
B = {0.1/1 + 0.2/2 + 0.2/3 + 0/4}
µ(A+B) = µ(A) + µ(B) - (µ(A) * µ(B))
Algebricsum = {0.3/1 + 0.5/2 + 0.6/3 + 0.5/4} - {0.02/1 + 0.06/2 + 0.08/3 + 0/4}
Algebricsum = {0.28/1 + 0.44/2 + 0.52/3 + 0.5/4}

# ALGEBRIC PRODUCT
A = {0.2/1 + 0.3/2 + 0.4/3 + 0.5/4}
B = {0.1/1 + 0.2/2 + 0.2/3 + 0/4}
µ(A*B) = (µ(A) * µ(B))
AlgebricProduct = {0.02/1 + 0.06/2 + 0.08/3 + 0/4}



{10, 11, 12, 13, 14, 15}
{11, 12, 13}
{14, 15}


2.Implementation of Fuzzy Relation (Max-Min Composition)

Max-min composition is a method ofcombining two fuzzy relations to create a new 
fuzzy relation. It is a common operation in fuzzy logic and is used to model 
complex relationships between fuzzy sets. 
Given two fuzzy relations R and S defined on the same universe of discourse X, 
the max-min composition of R and S, denoted by R∘S, is a fuzzy relation on X×X 
defined as follows: 
(R∘S)(x, z) = max(min(R(x, y), S(y, z))) for all x, z ϵ X, where y ϵ X. 
Intuitively, the max-min composition of R and S can be thought of as a "transitive 
closure" of R and S. That is, if R (x, y) and S(y, z) are both high (i.e., close to 1), 
then the composition (R∘S)(x, z) will also be high. Conversely, if either R (x, y) or 
S (y, z) is low (i.e., close to 0), then the composition (R∘S)(x, z) will be low. 
One important property of max-min composition is that it is associative, meaning 
that (R∘S) ∘T = R∘(S∘T) for all fuzzy relations R, S, and T. This property allows us 
to chain together multiple fuzzy relations to model more complex relationships. 
In practice, the max-min composition of two fuzzy relations can be computed by 
taking the minimum of the maximum of the minimum values of the corresponding 
rows of the two relations. This is often implemented using matrix multiplication or 
other efficient algorithms. 

In [9]:
import numpy as np
A = [
    [0.5, 0.2, 0.3],
    [0.1, 0.7, 0.6],
    [0.3, 0.5, 0.8]
    ]

B = [
    [0.6, 0.3, 0.1],
    [0.2, 0.5, 0.8],
    [0.8, 0.1, 0.5]
    ]

A = np.array(A)
B = np.array(B)

T = np.zeros((len(A),len(B)))

for i in range(len(A)):
    for j in range(len(B)):
        T[i,j] = np.max(np.minimum(A[i,:], B[:,j]))

print("Max-Min Composition:\n",T)


Max-Min Composition:
 [[0.5 0.3 0.3]
 [0.6 0.5 0.7]
 [0.8 0.5 0.5]]


3.Implementation of Simple Neural Network

The McCulloch-Pitts model is a simple model of a neuron, proposed by Warren McCulloch and 
Walter Pitts in 1943. It is a simplified model of a biological neuron and is based on the idea that 
a neuron receives inputs from other neurons or sensory organs and produces an output based on 
these inputs. 
The McCulloch-Pitts model consists of a set of binary inputs, a set of weights associated with 
each input, and a threshold. The neuron computes the weighted sum of the inputs and compares it 
to the threshold. If the weighted sum is greater than or equal to the threshold, the neuron 
produces an output of 1. Otherwise, it produces an output of 0. 
Formally, let x1, x2, ..., xn be the binary inputs w1, w2, ..., wn be the weights associated with 
each input, and θ be the threshold. Then the output y of the neuron is given by: 
y = 1 if ∑(xi * wi) >= θ
 0 otherwise 
Where ∑(xi * wi) represents the weighted sum of the inputs.
The McCulloch-Pitts model is a building block for more complex neural networks and has been 
used in various applications such as pattern recognition, signal processing, and control systems. 
It is a simple yet powerful model that can capture complex nonlinear relationships between 
inputs and outputs. 


In [10]:
def threshold(x):
    if x >= 0:
        return 1
    else:
        return 0

def mcCulloh_pitts(inputs,weights):
    weighted_sum = sum([inputs[i]*weights[i] for i in range(len(inputs))])
    output = threshold(weighted_sum)
    return output

inputs = [1,0,1]
weights = [0.5,-0.5,0.5]
output = mcCulloh_pitts(inputs,weights)
print("The Final Output is {}".format(output))

The Final Output is 1


4.Implement Single Layer Perceptron

The perceptron learning rule can be summarized as follows:

1. Initialize the weights of the network to small random values. 2. For each training example:

a. Compute the output of the network based on the current weights. b. Compare the predicted output to the actual output.

c. If the predicted output is incorrect, adjust the weights of the network in the direction of the correct output.

3. Repeat step 2 until the network achieves a satisfactory level of performance on the training data.

In [15]:
from sklearn.linear_model import Perceptron
import numpy as np
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([0, 0, 0, 1])
clf = Perceptron()
clf.fit(X, y)
test_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
predictions = clf.predict(test_data)
print(predictions)

# Scratch
import numpy as np

# Input data
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

# Output data
Y = np.array([[0], [0], [0], [1]])

# Step function
def step_function(x):
    return np.where(x > 0, 1, 0)

# Initialize weights and bias
W = np.random.rand(2, 1)
b = np.random.rand(1)

# Learning rate
lr = 0.1

# Training the model
for i in range(10000):
    # Forward propagation
    Z = np.dot(X, W) + b
    A = step_function(Z)

    # Backward propagation
    error = Y - A
    dW = lr * np.dot(X.T, error)
    db = lr * np.sum(error)

    # Update weights and bias
    W += dW
    b += db

# Testing the model
test_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
for x in test_data:
    result = step_function(np.dot(x, W) + b)
    print(f"{x[0]} AND {x[1]} = {result}")


[0 0 0 1]
0 AND 0 = [0]
0 AND 1 = [0]
1 AND 0 = [0]
1 AND 1 = [1]


5.Apply Hebbs and Delta Rule

Hebbian Learning Rule Algorithm

1. Set all weights to re 0 for inlaid base

2. For each input vector, S (oput vector) target output pair, repeat steps 3-1 3. Set activations for input with the input vector X 4. Set the corresponding output to the outpist for 1-1 to a

5 Update weight and bias by applying Hebb role for all (-1 to a

w, (now)=w, (old)+xy

b(new)= b (old)+y

The Delta learing pervised learning algorithm used for updating the wigs of neural

setwork during the tiny peces 50 90

NBX The Delta leuning enged to mimire the error between the posted it off work and the actual output. It does this by adjusting die-waights of the network in the direction it reduces the erre

The Delta learning rule work follows:

1. The network receives an input Vectothich is malplied by the weights to produce the output 2. The output is compared to the actual output to calculate the enor 3. The weights are adjusted based on the error and the learning rate. The learning rate is a param

that determines the size of the weight update 4. The process is repeatest for each input Vector in the training se

In Mathematical in the delix nile is as follows

delta w = n (t-y) x

In [17]:
# Hebbs Rule
import numpy as np
X = np.array([[1,0,0],[0,1,0],[0,0,1],[-1,0,0],[0,-1,0],[0,0,-1]])
W = np.random.rand(3,3)
lr = 0.1
for i in range(X.shape[0]):
    x = X[i].reshape(-1,1)
    W += lr * np.dot(x,x.T)
print(W)


[[0.77955031 0.22553648 0.98385229]
 [0.26299372 0.32367958 0.69123334]
 [0.84606871 0.74841357 0.25119327]]


In [19]:
# Delta Rule
X = np.array([[1,0,0],[0,1,0],[0,0,1],[-1,0,0],[0,-1,0],[0,0,-1]])
Y = np.array([[1],[1],[1],[-1],[-1],[-1],])
W = np.random.rand(3,1)
lr = 0.1

for i in range(X.shape[0]):
    x = X[i].reshape(-1,1)
    error = Y[i] - np.dot(W.T,x)
    W += lr * error * x
print(W)


[[0.47757617]
 [0.94216636]
 [0.5126008 ]]


6.Write a program for Error Back Propogation Algorithm(EBPA) Learning

Step 1: Inputs X, arrive through the preconnected path. 
Step 2: The input is modeled using true weights W. Weights are usually chosen randomly. 
Step 3: Calculate the output of each neuron from the input layer to the hidden layer to the output layer. 
Step 4: Calculate the error in the outputs 
Backpropagation Error= Actual Output – Desired Output 
Step 5: From the output layer, go back to the hidden layer to adjust the weights to reduce the error. 
Step 6: Repeat the process until the desired output is achieved. 
• x = inputs training vector x=(x1,x2,…………xn). 
• t = target vector t=(t1,t2……………tn).
• δk = error at output unit. 
• δj = error at hidden layer. 
• α = learning rate. 
• V0j = bias of hidden unit j. Training Algorithm :
Step 1: Initialize weight to small random values. 
Step 2: While the steps stopping condition is to be false do step 3 to 10. 
Step 3: For each training pair do step 4 to 9 (Feed-Forward). 
Step 4: Each input unit receives the signal unit and transmits the signal xi signal to all the units. 
Step 5 : Each hidden unit Zj (z=1 to a) sums its weighted input signal to calculate its net input 
zinj = v0j + Σxivij ( i=1 to n) 
 Applying activation function zj = f(zinj) and sends this signals to all units in the layer about i.e 
output units 
 For each output l=unit yk = (k=1 to m) sums its weighted input signals. 
 yink = w0k + Σ ziwjk (j=1 to a) and applies its 
activation function to calculate the output signals. yk = 
f(yink) 
Backpropagation Error :
Step 6: Each output unit yk (k=1 to n) receives a target pattern corresponding to an input pattern then 
error is calculated as: 
 δk = ( tk – yk ) + yink 
Step 7: Each hidden unit Zj (j=1 to a) sums its input from all units in the layer above 
δinj = Σ δj wjk 
 The error information term is calculated as : 
δj = δinj + zinj
Updation of weight and bias :
Step 8: Each output unit yk (k=1 to m) updates its bias and weight (j=1 to a). The weight correction term 
is given by : 
 Δ wjk = α δk zj and the bias 
correction term is given by Δwk = α δk.
 therefore wjk(new) = wjk(old) + Δ wjk
 w0k(new) = wok(old) + Δ wok
 for each hidden unit zj (j=1 to a) update its bias and weights (i=0 to n) the weight connection term 
 Δ vij = α δj xi 
and the bias connection on term 
 Δ v0j = α δj

In [ ]:
import numpy as np

# Define sigmoid activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Define derivative of sigmoid activation function
def sigmoid_derivative(x):
    return x * (1 - x)

# Define training data
X = np.array([[0, 0, 1],
              [0, 1, 1],
              [1, 0, 1],
              [1, 1, 1]])

y = np.array([[0],
              [1],
              [1],
              [0]])

# Define hyperparameters
learning_rate = 0.1
num_epochs = 10000
num_hidden_units = 4

# Initialize weights
input_dim = X.shape[1]
output_dim = y.shape[1]

W1 = np.random.randn(input_dim, num_hidden_units)
b1 = np.zeros((1, num_hidden_units))

W2 = np.random.randn(num_hidden_units, output_dim)
b2 = np.zeros((1, output_dim))

# Train the network using backpropagation
for epoch in range(num_epochs):
    # Forward pass
    z1 = np.dot(X, W1) + b1
    a1 = sigmoid(z1)
    
    z2 = np.dot(a1, W2) + b2
    a2 = sigmoid(z2)
    
    # Compute error
    error = y - a2
    
    # Backward pass
    delta2 = error * sigmoid_derivative(a2)
    dW2 = np.dot(a1.T, delta2)
    db2 = np.sum(delta2, axis=0, keepdims=True)
    
    delta1 = np.dot(delta2, W2.T) * sigmoid_derivative(a1)
    dW1 = np.dot(X.T, delta1)
    db1 = np.sum(delta1, axis=0, keepdims=True)
    
    # Update weights
    W2 += learning_rate * dW2
    b2 += learning_rate * db2
    W1 += learning_rate * dW1
    b1 += learning_rate * db1
    
# Predict output for new input
new_input = np.array([[1, 0, 0]])
z1 = np.dot(new_input, W1) + b1
a1 = sigmoid(z1)

z2 = np.dot(a1, W2) + b2
a2 = sigmoid(z2)

print(a2)


[[0.72128524]]


9.Design a fuzzy controller

In [32]:
import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl

# Define input variables
water_level = ctrl.Antecedent(np.arange(0, 11, 1), 'water_level')
dirt_level = ctrl.Antecedent(np.arange(0, 11, 1), 'dirt_level')

# Define output variable
detergent_amount = ctrl.Consequent(np.arange(0, 11, 1), 'detergent_amount')

# Define membership functions for input variables
water_level['low'] = fuzz.trimf(water_level.universe, [0, 0, 5])
water_level['medium'] = fuzz.trimf(water_level.universe, [0, 5, 10])
water_level['high'] = fuzz.trimf(water_level.universe, [5, 10, 10])

dirt_level['low'] = fuzz.trimf(dirt_level.universe, [0, 0, 5])
dirt_level['medium'] = fuzz.trimf(dirt_level.universe, [0, 5, 10])
dirt_level['high'] = fuzz.trimf(dirt_level.universe, [5, 10, 10])

# Define membership functions for output variable
detergent_amount['low'] = fuzz.trimf(detergent_amount.universe, [0, 0, 5])
detergent_amount['medium'] = fuzz.trimf(detergent_amount.universe, [0, 5, 10])
detergent_amount['high'] = fuzz.trimf(detergent_amount.universe, [5, 10, 10])

# Define fuzzy rules
rule1 = ctrl.Rule(water_level['low'] & dirt_level['low'], detergent_amount['low'])
rule2 = ctrl.Rule(water_level['low'] & dirt_level['medium'], detergent_amount['low'])
rule3 = ctrl.Rule(water_level['low'] & dirt_level['high'], detergent_amount['medium'])
rule4 = ctrl.Rule(water_level['medium'] & dirt_level['low'], detergent_amount['low'])
rule5 = ctrl.Rule(water_level['medium'] & dirt_level['medium'], detergent_amount['medium'])
rule6 = ctrl.Rule(water_level['medium'] & dirt_level['high'], detergent_amount['high'])
rule7 = ctrl.Rule(water_level['high'] & dirt_level['low'], detergent_amount['medium'])
rule8 = ctrl.Rule(water_level['high'] & dirt_level['medium'], detergent_amount['high'])
rule9 = ctrl.Rule(water_level['high'] & dirt_level['high'], detergent_amount['high'])

# Define control system
washing_machine_ctrl = ctrl.ControlSystem(
    [rule1, rule2, rule3, rule4, rule5, rule6, rule7, rule8, rule9])

# Define simulation
washing_machine_sim = ctrl.ControlSystemSimulation(washing_machine_ctrl)

# Set input values
washing_machine_sim.input['water_level'] = 3
washing_machine_sim.input['dirt_level'] = 7

# Run simulation
washing_machine_sim.compute()

# Print output value
print(washing_machine_sim.output['detergent_amount'])


4.999999999999998


In [27]:
pip install numpy scipy

Note: you may need to restart the kernel to use updated packages.


In [30]:
pip install -U scikit-fuzzy


  Created wheel for scikit-fuzzy: filename=scikit_fuzzy-0.4.2-py3-none-any.whl size=894089 sha256=9374a7294ed976eecab0710280a197ae633bf39fdde77ba8d718d9709174f780
  Stored in directory: c:\users\admin\appdata\local\pip\cache\wheels\32\2c\a1\a90a7d7dd8448ec029f298a61f3490275e99b17aa348be675c
Successfully built scikit-fuzzy
